import Head from "next/head";
import { blogPosts } from "../../lib/data";

export default function BlogPage({ title, date, content }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='mt-6 border-b-2 mb-4'>
          <h1 className='text-3xl mb-2 text-[#aee8ff] font-semibold'>
            {title}
          </h1>
          <p className='text-grey-400 mb-1 font-space  text-s'>• {date} •</p>
        </div>

        <p className='text-justify'>{content}</p>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const { params } = context;
  return {
    props: blogPosts.find((item) => item.slug === params.slug),
  };
}

export async function getStaticPaths(context) {
  return {
    paths: blogPosts.map((item) => ({
      params: {
        slug: item.slug,
      },
    })),
    fallback: false,
  };
}
