import Head from "next/head";
import Image from "next/image";

export default function About() {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>About</h1>
      </main>
    </div>
  );
}
