import Head from "next/head";
import BlogPost from "../components/blogPost";
import { getPostSlugs } from "../lib/data";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>My Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        {data.map((item) => (
          <BlogPost
            key={item.slug}
            slug={item.slug}
            title={item.data.title}
            content={item.content}
            date={item.data.date}
          />
        ))}
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const data = getPostSlugs();
  return {
    props: {
      data,
    },
  };
}
